"""Initial migration

Revision ID: 001_initial
Revises:
Create Date: 2024-03-19

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Commands auto generated by Alembic - please adjust! ###

    # Create screens table
    op.create_table(
        'screens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('activity', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create elements table
    op.create_table(
        'elements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('screen_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'screen_id', name='uq_element_name_screen')
    )

    # Create locators table
    op.create_table(
        'locators',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('element_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create tags table
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('color', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create steps table
    op.create_table(
        'steps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('screen_id', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(length=50), nullable=False),
        sa.Column('element_id', sa.Integer(), nullable=True),
        sa.Column('action_value', sa.Text(), nullable=True),
        sa.Column('assert_config', sa.JSON(), nullable=True),
        sa.Column('wait_after_ms', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create step_tags association table
    op.create_table(
        'step_tags',
        sa.Column('step_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('step_id', 'tag_id')
    )

    # Create flows table
    op.create_table(
        'flows',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('flow_type', sa.Enum('standard', 'dsl', 'python', name='flow_type_enum'), nullable=False),
        sa.Column('requires', sa.JSON(), nullable=True),
        sa.Column('default_params', sa.JSON(), nullable=True),
        sa.Column('dsl_content', sa.Text(), nullable=True),
        sa.Column('py_file', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create flow_steps table
    op.create_table(
        'flow_steps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('flow_id', sa.Integer(), nullable=False),
        sa.Column('step_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('override_value', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create flow_tags association table
    op.create_table(
        'flow_tags',
        sa.Column('flow_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('flow_id', 'tag_id')
    )

    # Create testcases table
    op.create_table(
        'testcases',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority_enum'), nullable=False),
        sa.Column('timeout', sa.Integer(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create testcase_flows table
    op.create_table(
        'testcase_flows',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('testcase_id', sa.Integer(), nullable=False),
        sa.Column('flow_id', sa.Integer(), nullable=False),
        sa.Column('flow_role', sa.Enum('setup', 'main', 'teardown', name='flow_role_enum'), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Integer(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create testcase_inline_steps table
    op.create_table(
        'testcase_inline_steps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('testcase_id', sa.Integer(), nullable=False),
        sa.Column('step_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('override_value', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create testcase_tags association table
    op.create_table(
        'testcase_tags',
        sa.Column('testcase_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('testcase_id', 'tag_id')
    )

    # Create suites table
    op.create_table(
        'suites',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='suite_priority_enum'), nullable=False),
        sa.Column('enabled', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create suite_testcases table
    op.create_table(
        'suite_testcases',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('suite_id', sa.Integer(), nullable=False),
        sa.Column('testcase_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create profile_tags association table
    op.create_table(
        'profile_tags',
        sa.Column('profile_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('profile_id', 'tag_id')
    )

    # Create profiles table
    op.create_table(
        'profiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('variables', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create data_store table
    op.create_table(
        'data_store',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('env', sa.String(length=100), nullable=False),
        sa.Column('key_name', sa.String(length=200), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('env', 'key_name', name='uq_env_key')
    )

    # Create devices table
    op.create_table(
        'devices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('serial', sa.String(length=100), nullable=False),
        sa.Column('model', sa.String(length=100), nullable=True),
        sa.Column('os_version', sa.String(length=50), nullable=True),
        sa.Column('connection_type', sa.Enum('usb', 'tcp', name='connection_type_enum'), nullable=False),
        sa.Column('ip_port', sa.String(length=50), nullable=True),
        sa.Column('capabilities', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('serial')
    )

    # Create run_history table
    op.create_table(
        'run_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_id', sa.String(length=100), nullable=False),
        sa.Column('type', sa.Enum('testcase', 'suite', name='run_type_enum'), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=False),
        sa.Column('target_name', sa.String(length=200), nullable=False),
        sa.Column('result', sa.Enum('pending', 'running', 'pass', 'fail', 'cancelled', 'timeout', name='run_result_enum'), nullable=False),
        sa.Column('returncode', sa.Integer(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('profile_id', sa.Integer(), nullable=True),
        sa.Column('profile_name', sa.String(length=100), nullable=True),
        sa.Column('device_serial', sa.String(length=100), nullable=True),
        sa.Column('device_name', sa.String(length=100), nullable=True),
        sa.Column('has_screenshots', sa.Integer(), nullable=False),
        sa.Column('log_path', sa.String(length=500), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id')
    )

    # Create backups table
    op.create_table(
        'backups',
        sa.Column('id', sa.String(length=100), primary_key=True),
        sa.Column('resource', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('size_bytes', sa.BigInteger(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### Commands auto generated by Alembic - please adjust! ###
    op.drop_table('backups')
    op.drop_table('run_history')
    op.drop_table('devices')
    op.drop_table('data_store')
    op.drop_table('profiles')
    op.drop_table('profile_tags')
    op.drop_table('suite_testcases')
    op.drop_table('suites')
    op.drop_table('testcase_tags')
    op.drop_table('testcase_inline_steps')
    op.drop_table('testcase_flows')
    op.drop_table('testcases')
    op.drop_table('flow_tags')
    op.drop_table('flow_steps')
    op.drop_table('flows')
    op.drop_table('step_tags')
    op.drop_table('steps')
    op.drop_table('tags')
    op.drop_table('locators')
    op.drop_table('elements')
    op.drop_table('screens')
    # ### end Alembic commands ###
